# Generated by Django 4.0 on 2024-09-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='mycustomuser',
            name='fullName',
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
