# Generated by Django 4.0 on 2024-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0002_remove_mycustomuser_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
