# Generated by Django 4.0 on 2024-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0003_alter_mycustomuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
